
#- name: test for available disk space
#  assert:
#    that:
#     - "{{ item.size_available > 500 * 1000 * 1000 }}" # 500Mb
#  when: "{{ item.mount == '/' }}"
#  with_items: "{{ ansible_mounts }}"


# We need custom handling for BerryBoot as it lacks `/boot`.
# To detect this, the image creates `/etc/berryboot`.
- stat:
    path: /etc/berryboot
  register: berryboot

- set_fact: is_berryboot="{{berryboot.stat.exists}}"

- debug:
    msg: "Detected BerryBoot installation."
  when: is_berryboot

- name: Mount boot on BerryBoot
  mount:
    name=/boot
    src=/dev/mmcblk0p1
    fstype=vfat
    state=mounted
  when: is_berryboot

- name: Make sure we have proper framebuffer depth
  lineinfile:
    dest: /boot/config.txt
    regexp: ^framebuffer_depth=
    line: framebuffer_depth=32

- name: Fix framebuffer bug
  lineinfile:
    dest: /boot/config.txt
    regexp: ^framebuffer_ignore_alpha=
    line: framebuffer_ignore_alpha=1

- name: Backup kernel boot args
  copy:
    src: /boot/cmdline.txt
    dest: /boot/cmdline.txt.orig
    force: no

- debug:
    msg: "Use cmdline.txt.orig for boot parameters (don't remove this file)"

- copy:
    src: /boot/cmdline.txt.orig
    dest: /boot/cmdline.txt
    force: yes

- name: Use Systemd as init and quiet boot process
  lineinfile:
    dest: /boot/cmdline.txt
    regexp: (.*)
    backrefs: yes
    line: \1 quiet init=/lib/systemd/systemd

- name: Install Screenly dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - matchbox
    - omxplayer
    - python-netifaces
    - python-simplejson
    - sqlite3
    - systemd
    - uzbl
    - x11-xserver-utils
    - xserver-xorg

- name: Install systemd-sysv on Wheezy
  command: bash -c 'echo "Yes, do as I say!" | apt-get install -y --force-yes systemd-sysv'
  when: ansible_distribution_release == "wheezy"

- name: Remove deprecated apt dependencies
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - supervisor
    - lightdm
    - lightdm-gtk-greeter
    - dphys-swapfile

- name: Perform system upgrade
  apt:
    upgrade: dist
  tags:
    - system-upgrade

- name: Clean up unused packages
  command: apt-get -y autoremove
  tags:
    - system-upgrade

- name: Remove deprecated pip dependencies
  pip:
    name: supervisor
    state: absent

- name: Copy in rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: 0755
    owner: root
    group: root

- name: Clear out X11 configs (disables touchpad and other unnecessary things)
  file:
    path: "/usr/share/X11/xorg.conf.d/{{ item }}"
    state: absent
  with_items:
    - 10-evdev.conf
    - 50-synaptics.conf
    - 10-quirks.conf
    - 50-wacom.conf

- name: Disable swap
  command: /sbin/swapoff --all removes=/var/swap

- name: Remove swapfile from disk
  file:
    path: /var/swap
    state: absent
